version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/usr/src'
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
  client:
    build: ./docker/vue
    container_name: front
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./front:/app
    tty: true
    stdin_open: true
  app:
    build: ./docker/python
    volumes:
      - ./server:/var/www/html
    tty: true
  db:
    image: mariadb:latest

    volumes:
      -  ./dbdata:/var/lib/mysql
    ports:
        - "3307:3306"
    expose:
        - "3307"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "hoge"
volumes:
  dbdata:

