# Generated by Django 3.2.12 on 2023-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filepath', models.TextField()),
                ('iconName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'icon',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'drink',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('loginID', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('deleteDate', models.DateField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
