# Generated by Django 3.2.12 on 2023-03-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_imageupload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageupload',
            table='image',
        ),
    ]
